export const products = [
  {
    id: 1,
    name: "Wireless Noise-Canceling Headphones",
    slug: "wireless-noise-canceling-headphones",
    price: 1250000,
    stock: 25,
    category: 1,
    category_name: "Electronics",
    rating: 5,
    img: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&q=80",
    description: "Headphone nirkabel premium dengan teknologi active noise-canceling untuk pengalaman mendengarkan musik tanpa gangguan serta baterai tahan hingga 30 jam."
  },
  {
    id: 2,
    name: "Smartwatch Series 7 Pro",
    slug: "smartwatch-series-7-pro",
    price: 1850000,
    stock: 15,
    category: 1,
    category_name: "Electronics",
    rating: 4,
    img: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&q=80",
    description: "Jam tangan pintar dengan pemantau detak jantung, GPS akurat, dan layar AMOLED tahan air yang cocok untuk menunjang gaya hidup aktif Anda."
  },
  {
    id: 3,
    name: "Minimalist Leather Backpack",
    slug: "minimalist-leather-backpack",
    price: 650000,
    stock: 20,
    category: 2,
    category_name: "Fashion",
    rating: 5,
    img: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80",
    description: "Tas ransel berbahan kulit sintetis premium berdesain minimalis modern. Dilengkapi kompartemen laptop 15 inci yang aman dan elegan untuk kerja atau kuliah."
  },
  {
    id: 4,
    name: "Classic Denim Vintage Jacket",
    slug: "classic-denim-vintage-jacket",
    price: 499000,
    stock: 12,
    category: 2,
    category_name: "Fashion",
    rating: 4,
    img: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=500&q=80",
    description: "Jaket jeans klasik bergaya vintage dengan potongan regular fit yang nyaman dipakai sehari-hari untuk melengkapi gaya streetwear Anda."
  },
  {
    id: 5,
    name: "Ergonomic Mechanical Keyboard",
    slug: "ergonomic-mechanical-keyboard",
    price: 950000,
    stock: 30,
    category: 1,
    category_name: "Electronics",
    rating: 5,
    img: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500&q=80",
    description: "Keyboard mekanis dengan RGB lighting kustom dan switch responsif untuk kenyamanan mengetik maksimal serta performa gaming profesional."
  },
  {
    id: 6,
    name: "Minimalist Ceramic Coffee Mug",
    slug: "minimalist-ceramic-coffee-mug",
    price: 125000,
    stock: 50,
    category: 3,
    category_name: "Lifestyle",
    rating: 4,
    img: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&q=80",
    description: "Mug keramik estetis tahan panas berkapasitas 350ml, cocok untuk menemani pagi hari Anda saat menikmati kopi atau teh hangat."
  },
  {
    id: 7,
    name: "Modern Aviator Sunglasses",
    slug: "modern-aviator-sunglasses",
    price: 350000,
    stock: 18,
    category: 4,
    category_name: "Accessories",
    rating: 5,
    img: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500&q=80",
    description: "Kacamata hitam bergaya aviator modern dengan perlindungan UV400 penuh untuk melindungi mata dari teriknya sinar matahari sekaligus menunjang penampilan."
  },
  {
    id: 8,
    name: "Running Sport Sneakers",
    slug: "running-sport-sneakers",
    price: 899000,
    stock: 22,
    category: 2,
    category_name: "Fashion",
    rating: 5,
    img: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80",
    description: "Sepatu lari ringan dengan sol empuk berteknologi tinggi yang memberikan kenyamanan maksimal saat berolahraga maupun aktivitas harian."
  },
  {
    id: 9,
    name: "Portable Bluetooth Speaker",
    slug: "portable-bluetooth-speaker",
    price: 550000,
    stock: 14,
    category: 1,
    category_name: "Electronics",
    rating: 4,
    img: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&q=80",
    description: "Speaker portabel tahan air dengan kualitas suara bass mendalam dan koneksi Bluetooth stabil untuk menemani petualangan outdoor Anda."
  },
  {
    id: 10,
    name: "Casual Canvas Tote Bag",
    slug: "casual-canvas-tote-bag",
    price: 175000,
    stock: 40,
    category: 2,
    category_name: "Fashion",
    rating: 4,
    img: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=500&q=80",
    description: "Tas tote kanvas tebal berkapasitas luas yang kuat dan ramah lingkungan, cocok untuk kuliah, belanja, atau jalan-jalan santai."
  },
  {
    id: 11,
    name: "Professional DSLR Camera Lens",
    slug: "professional-dslr-camera-lens",
    price: 3450000,
    stock: 5,
    category: 1,
    category_name: "Electronics",
    rating: 5,
    img: "https://images.unsplash.com/photo-1617005082133-5c5f425b0cb1?w=500&q=80",
    description: "Lensa kamera profesional dengan bukaan diafragma besar untuk menghasilkan foto tajam berlatar belakang blur (bokeh) yang artistik."
  },
  {
    id: 12,
    name: "Stainless Steel Tumbler 500ml",
    slug: "stainless-steel-tumbler-500ml",
    price: 220000,
    stock: 35,
    category: 3,
    category_name: "Lifestyle",
    rating: 5,
    img: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500&q=80",
    description: "Botol minum termal berbahan stainless steel berkualitas tinggi yang mampu menjaga suhu air panas atau dingin hingga 12 jam."
  },
  {
    id: 13,
    name: "Ultra-Wide Gaming Monitor 27\"",
    slug: "ultra-wide-gaming-monitor-27",
    price: 3100000,
    stock: 8,
    category: 1,
    category_name: "Electronics",
    rating: 5,
    img: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500&q=80",
    description: "Monitor gaming beresolusi tinggi dengan refresh rate 165Hz untuk pengalaman bermain game dan produktivitas kerja tanpa batas."
  },
  {
    id: 14,
    name: "Premium Cotton Hoodie",
    slug: "premium-cotton-hoodie",
    price: 320000,
    stock: 25,
    category: 2,
    category_name: "Fashion",
    rating: 4,
    img: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=500&q=80",
    description: "Hoodie berbahan katun fleece tebal yang lembut dan hangat, memberikan kenyamanan maksimal untuk gaya kasual sehari-hari."
  },
  {
    id: 15,
    name: "Smart LED Desk Lamp",
    slug: "smart-led-desk-lamp",
    price: 280000,
    stock: 20,
    category: 3,
    category_name: "Lifestyle",
    rating: 4,
    img: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&q=80",
    description: "Lampu meja LED pintar dengan pengatur tingkat kecerahan sentuh dan mode warna cahaya yang aman untuk kesehatan mata saat bekerja."
  },
  {
    id: 16,
    name: "Minimalist Leather Wallet",
    slug: "minimalist-leather-wallet",
    price: 195000,
    stock: 30,
    category: 4,
    category_name: "Accessories",
    rating: 5,
    img: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=500&q=80",
    description: "Dompet kulit asli berdesain tipis dan elegan yang muat banyak kartu serta uang tunai tanpa membuat saku celana menonjol."
  }
];